kind: Deployment
apiVersion: apps/v1
metadata:
  name: python-39-cheap
  namespace: fmv3
  labels:
    app: python-39-cheap
    app.kubernetes.io/component: python-39-cheap
    app.kubernetes.io/instance: python-39-cheap
    app.kubernetes.io/name: python-39-cheap
    app.kubernetes.io/part-of: python-39-app-cheap
    app.openshift.io/runtime: python
    app.openshift.io/runtime-namespace: fmv3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-39-cheap
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-39-cheap
        deploymentconfig: python-39-cheap
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      containers:
        - name: python-39-cheap
          image: 'quay.io/ml-aml-workshop/gpu-slicing:tf'
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: 2Gi
              nvidia.com/gpu: '0'
            requests:
              memory: 1Gi
              nvidia.com/gpu: '0'
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nvidia.com/gpu.present
                    operator: In
                    values:
                      - 'true'
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
